version: "3.9"
services:
  db:
    container_name: postgres_container
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgre_config:/etc/postgresql.conf
      - postgre_persistence:/var/lib/postgresql
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  postgre_persistence:
    external: true
  postgre_config:
    external: true